// Code generated by protoc-gen-go. DO NOT EDIT.
// source: observer.proto

package observer

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StateType int32

const (
	StateType_OPEN_NOTRUNNING                     StateType = 0
	StateType_OPEN_NOTRUNNING_SUSPENDED           StateType = 1
	StateType_OPEN_RUNNING                        StateType = 2
	StateType_CLOSED_COMPLETED                    StateType = 3
	StateType_CLOSED_ABNORMALCOMPLETED            StateType = 4
	StateType_CLOSED_ABNORMALCOMPLETED_TERMINATED StateType = 5
	StateType_CLOSED_ABNORMALCOMPLETED_ABORTED    StateType = 6
)

var StateType_name = map[int32]string{
	0: "OPEN_NOTRUNNING",
	1: "OPEN_NOTRUNNING_SUSPENDED",
	2: "OPEN_RUNNING",
	3: "CLOSED_COMPLETED",
	4: "CLOSED_ABNORMALCOMPLETED",
	5: "CLOSED_ABNORMALCOMPLETED_TERMINATED",
	6: "CLOSED_ABNORMALCOMPLETED_ABORTED",
}

var StateType_value = map[string]int32{
	"OPEN_NOTRUNNING":                     0,
	"OPEN_NOTRUNNING_SUSPENDED":           1,
	"OPEN_RUNNING":                        2,
	"CLOSED_COMPLETED":                    3,
	"CLOSED_ABNORMALCOMPLETED":            4,
	"CLOSED_ABNORMALCOMPLETED_TERMINATED": 5,
	"CLOSED_ABNORMALCOMPLETED_ABORTED":    6,
}

func (x StateType) String() string {
	return proto.EnumName(StateType_name, int32(x))
}

func (StateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f64efb003ca9295a, []int{0}
}

type GetPropertiesRq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPropertiesRq) Reset()         { *m = GetPropertiesRq{} }
func (m *GetPropertiesRq) String() string { return proto.CompactTextString(m) }
func (*GetPropertiesRq) ProtoMessage()    {}
func (*GetPropertiesRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f64efb003ca9295a, []int{0}
}

func (m *GetPropertiesRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPropertiesRq.Unmarshal(m, b)
}
func (m *GetPropertiesRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPropertiesRq.Marshal(b, m, deterministic)
}
func (m *GetPropertiesRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPropertiesRq.Merge(m, src)
}
func (m *GetPropertiesRq) XXX_Size() int {
	return xxx_messageInfo_GetPropertiesRq.Size(m)
}
func (m *GetPropertiesRq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPropertiesRq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPropertiesRq proto.InternalMessageInfo

type GetPropertiesRs struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPropertiesRs) Reset()         { *m = GetPropertiesRs{} }
func (m *GetPropertiesRs) String() string { return proto.CompactTextString(m) }
func (*GetPropertiesRs) ProtoMessage()    {}
func (*GetPropertiesRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_f64efb003ca9295a, []int{1}
}

func (m *GetPropertiesRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPropertiesRs.Unmarshal(m, b)
}
func (m *GetPropertiesRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPropertiesRs.Marshal(b, m, deterministic)
}
func (m *GetPropertiesRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPropertiesRs.Merge(m, src)
}
func (m *GetPropertiesRs) XXX_Size() int {
	return xxx_messageInfo_GetPropertiesRs.Size(m)
}
func (m *GetPropertiesRs) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPropertiesRs.DiscardUnknown(m)
}

var xxx_messageInfo_GetPropertiesRs proto.InternalMessageInfo

func (m *GetPropertiesRs) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type StateChangedRq struct {
	Sequence             []*StateChangedSequence `protobuf:"bytes,1,rep,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *StateChangedRq) Reset()         { *m = StateChangedRq{} }
func (m *StateChangedRq) String() string { return proto.CompactTextString(m) }
func (*StateChangedRq) ProtoMessage()    {}
func (*StateChangedRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f64efb003ca9295a, []int{2}
}

func (m *StateChangedRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateChangedRq.Unmarshal(m, b)
}
func (m *StateChangedRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateChangedRq.Marshal(b, m, deterministic)
}
func (m *StateChangedRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateChangedRq.Merge(m, src)
}
func (m *StateChangedRq) XXX_Size() int {
	return xxx_messageInfo_StateChangedRq.Size(m)
}
func (m *StateChangedRq) XXX_DiscardUnknown() {
	xxx_messageInfo_StateChangedRq.DiscardUnknown(m)
}

var xxx_messageInfo_StateChangedRq proto.InternalMessageInfo

func (m *StateChangedRq) GetSequence() []*StateChangedSequence {
	if m != nil {
		return m.Sequence
	}
	return nil
}

type StateChangedSequence struct {
	State                string   `protobuf:"bytes,1,opt,name=State,proto3" json:"State,omitempty"`
	PreviousState        string   `protobuf:"bytes,2,opt,name=PreviousState,proto3" json:"PreviousState,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateChangedSequence) Reset()         { *m = StateChangedSequence{} }
func (m *StateChangedSequence) String() string { return proto.CompactTextString(m) }
func (*StateChangedSequence) ProtoMessage()    {}
func (*StateChangedSequence) Descriptor() ([]byte, []int) {
	return fileDescriptor_f64efb003ca9295a, []int{3}
}

func (m *StateChangedSequence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateChangedSequence.Unmarshal(m, b)
}
func (m *StateChangedSequence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateChangedSequence.Marshal(b, m, deterministic)
}
func (m *StateChangedSequence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateChangedSequence.Merge(m, src)
}
func (m *StateChangedSequence) XXX_Size() int {
	return xxx_messageInfo_StateChangedSequence.Size(m)
}
func (m *StateChangedSequence) XXX_DiscardUnknown() {
	xxx_messageInfo_StateChangedSequence.DiscardUnknown(m)
}

var xxx_messageInfo_StateChangedSequence proto.InternalMessageInfo

func (m *StateChangedSequence) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *StateChangedSequence) GetPreviousState() string {
	if m != nil {
		return m.PreviousState
	}
	return ""
}

type StateChangedRs struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateChangedRs) Reset()         { *m = StateChangedRs{} }
func (m *StateChangedRs) String() string { return proto.CompactTextString(m) }
func (*StateChangedRs) ProtoMessage()    {}
func (*StateChangedRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_f64efb003ca9295a, []int{4}
}

func (m *StateChangedRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateChangedRs.Unmarshal(m, b)
}
func (m *StateChangedRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateChangedRs.Marshal(b, m, deterministic)
}
func (m *StateChangedRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateChangedRs.Merge(m, src)
}
func (m *StateChangedRs) XXX_Size() int {
	return xxx_messageInfo_StateChangedRs.Size(m)
}
func (m *StateChangedRs) XXX_DiscardUnknown() {
	xxx_messageInfo_StateChangedRs.DiscardUnknown(m)
}

var xxx_messageInfo_StateChangedRs proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("observer.StateType", StateType_name, StateType_value)
	proto.RegisterType((*GetPropertiesRq)(nil), "observer.GetPropertiesRq")
	proto.RegisterType((*GetPropertiesRs)(nil), "observer.GetPropertiesRs")
	proto.RegisterType((*StateChangedRq)(nil), "observer.StateChangedRq")
	proto.RegisterType((*StateChangedSequence)(nil), "observer.StateChangedSequence")
	proto.RegisterType((*StateChangedRs)(nil), "observer.StateChangedRs")
}

func init() { proto.RegisterFile("observer.proto", fileDescriptor_f64efb003ca9295a) }

var fileDescriptor_f64efb003ca9295a = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4d, 0x6f, 0x82, 0x40,
	0x10, 0x86, 0x8b, 0x56, 0xa3, 0x53, 0x3f, 0xe8, 0xd4, 0x03, 0x9a, 0xb6, 0x31, 0x68, 0x52, 0xd3,
	0x83, 0x07, 0x7b, 0xeb, 0x0d, 0x65, 0x63, 0x4c, 0x71, 0x21, 0x0b, 0x9e, 0x89, 0xb6, 0x9b, 0xd6,
	0x8b, 0x08, 0x8b, 0x26, 0xfe, 0x90, 0xfe, 0xb3, 0xfe, 0xa0, 0x06, 0xc4, 0x2f, 0x22, 0x37, 0xe6,
	0x7d, 0x1e, 0x32, 0x64, 0x5e, 0xa0, 0xe6, 0x2d, 0x04, 0x0f, 0xb6, 0x3c, 0xe8, 0xaf, 0x03, 0x2f,
	0xf4, 0xb0, 0x74, 0x98, 0xd5, 0x7b, 0xa8, 0x8f, 0x79, 0x68, 0x05, 0xde, 0x9a, 0x07, 0xe1, 0x92,
	0x0b, 0xe6, 0xab, 0x9d, 0x74, 0x24, 0x50, 0x86, 0xfc, 0x07, 0xdf, 0x29, 0x52, 0x5b, 0xea, 0x95,
	0x59, 0xf4, 0xa8, 0x1a, 0x50, 0xb3, 0xc3, 0x79, 0xc8, 0x47, 0x3f, 0xf3, 0xd5, 0x37, 0xff, 0x62,
	0x3e, 0xbe, 0x43, 0x49, 0x70, 0x7f, 0xc3, 0x57, 0x9f, 0x5c, 0x91, 0xda, 0xf9, 0xde, 0xdd, 0xe0,
	0xb9, 0x7f, 0x5c, 0x7b, 0xee, 0xda, 0x89, 0xc5, 0x8e, 0xbe, 0xca, 0xa0, 0x71, 0xcd, 0xc0, 0x06,
	0x14, 0xe2, 0x3c, 0xd9, 0xbc, 0x1f, 0xb0, 0x0b, 0x55, 0x2b, 0xe0, 0xdb, 0xa5, 0xb7, 0x11, 0x7b,
	0x9a, 0x8b, 0xe9, 0x65, 0xa8, 0xca, 0xa9, 0x2f, 0x14, 0xaf, 0x7f, 0x12, 0x94, 0x45, 0x14, 0x39,
	0xbb, 0x35, 0xc7, 0x07, 0xa8, 0x9b, 0x16, 0xa1, 0x2e, 0x35, 0x1d, 0x36, 0xa3, 0x74, 0x42, 0xc7,
	0xf2, 0x0d, 0x3e, 0x41, 0x33, 0x15, 0xba, 0xf6, 0xcc, 0xb6, 0x08, 0xd5, 0x89, 0x2e, 0x4b, 0x28,
	0x43, 0x25, 0xc6, 0x87, 0x17, 0x72, 0xd8, 0x00, 0x79, 0x64, 0x98, 0x36, 0xd1, 0xdd, 0x91, 0x39,
	0xb5, 0x0c, 0xe2, 0x10, 0x5d, 0xce, 0xe3, 0x23, 0x28, 0x49, 0xaa, 0x0d, 0xa9, 0xc9, 0xa6, 0x9a,
	0x71, 0xa2, 0xb7, 0xf8, 0x02, 0x9d, 0x2c, 0xea, 0x3a, 0x84, 0x4d, 0x27, 0x54, 0x8b, 0xc4, 0x02,
	0x76, 0xa1, 0x9d, 0x29, 0x6a, 0x43, 0x93, 0x45, 0x56, 0x71, 0xf0, 0x2b, 0x41, 0xc9, 0x4c, 0x0e,
	0x8d, 0x04, 0xaa, 0x17, 0xe5, 0x61, 0xf3, 0x54, 0x42, 0xaa, 0xe8, 0x56, 0x26, 0x12, 0x38, 0x84,
	0xca, 0xf9, 0xf1, 0x50, 0xb9, 0x5e, 0x25, 0xf3, 0x5b, 0x59, 0x44, 0x2c, 0x8a, 0xf1, 0xbf, 0xf6,
	0xf6, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xff, 0xf3, 0xb4, 0x60, 0x7d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ObserverClient is the client API for Observer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ObserverClient interface {
	GetProperties(ctx context.Context, in *GetPropertiesRq, opts ...grpc.CallOption) (*GetPropertiesRs, error)
	StateChanged(ctx context.Context, in *StateChangedRq, opts ...grpc.CallOption) (*StateChangedRs, error)
}

type observerClient struct {
	cc *grpc.ClientConn
}

func NewObserverClient(cc *grpc.ClientConn) ObserverClient {
	return &observerClient{cc}
}

func (c *observerClient) GetProperties(ctx context.Context, in *GetPropertiesRq, opts ...grpc.CallOption) (*GetPropertiesRs, error) {
	out := new(GetPropertiesRs)
	err := c.cc.Invoke(ctx, "/observer.Observer/GetProperties", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observerClient) StateChanged(ctx context.Context, in *StateChangedRq, opts ...grpc.CallOption) (*StateChangedRs, error) {
	out := new(StateChangedRs)
	err := c.cc.Invoke(ctx, "/observer.Observer/StateChanged", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObserverServer is the server API for Observer service.
type ObserverServer interface {
	GetProperties(context.Context, *GetPropertiesRq) (*GetPropertiesRs, error)
	StateChanged(context.Context, *StateChangedRq) (*StateChangedRs, error)
}

// UnimplementedObserverServer can be embedded to have forward compatible implementations.
type UnimplementedObserverServer struct {
}

func (*UnimplementedObserverServer) GetProperties(ctx context.Context, req *GetPropertiesRq) (*GetPropertiesRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProperties not implemented")
}
func (*UnimplementedObserverServer) StateChanged(ctx context.Context, req *StateChangedRq) (*StateChangedRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StateChanged not implemented")
}

func RegisterObserverServer(s *grpc.Server, srv ObserverServer) {
	s.RegisterService(&_Observer_serviceDesc, srv)
}

func _Observer_GetProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPropertiesRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserverServer).GetProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/observer.Observer/GetProperties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserverServer).GetProperties(ctx, req.(*GetPropertiesRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Observer_StateChanged_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateChangedRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserverServer).StateChanged(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/observer.Observer/StateChanged",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserverServer).StateChanged(ctx, req.(*StateChangedRq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Observer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "observer.Observer",
	HandlerType: (*ObserverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProperties",
			Handler:    _Observer_GetProperties_Handler,
		},
		{
			MethodName: "StateChanged",
			Handler:    _Observer_StateChanged_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "observer.proto",
}
